{
	"phones": [{
		"title": "Samsung GT-I9301I GALAXY S 3",
		"sim": "Micro-SIM",
		"simAmount": "1",
		"color": "Белый",
		"os": "Android",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "Есть",
		"vendorСode": "189238",
		"description": "Смартфон Samsung GT-I9301I GALAXY S 3 Ceramic White Моноблок, Micro-SIM, Android 4.4, 3G, Bluetooth 4.0, EDGE, GPRS, WAP, Wi-Fi, Количество ядер процессора 4, Частота процессора 1400 МГц",
		"price": "11290"
	}, 
	{
		"title": "Microsoft Lumia 640 RM-1077",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"vendorСode": "283135",
		"description": "Вместе с новой Microsoft Lumia 640 Dual SIM (RM-1077) вы открываете мир ярких цифровых возможностей. Этот многофункциональный смартфон уже содержит набор бесплатных сервисов Microsoft",
		"price": "10990"
	},
	{
		"title": "Archos 50 Oxygen Plus",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"vendorСode": "283135",
		"description": "Смартфон Archos 50 Oxygen Plus, серый. Моноблок, Micro-SIM, Android , 3G, Bluetooth, USB-подключение к ПК, Wi-Fi, Разрешение основной камеры 8 Мп",
		"price": "9900"
	},
	{
		"title": "Philips S398 Black",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"vendorСode": "283135",
		"description": "Смартфон Philips S398 Black. Черный корпус и разнообразие цветных панелей для Philips S398 как нельзя лучше подчеркнут ваш статус и уверенность в себе. Преимущества этой модели",
		"price": "8990"
	},
	{
		"title": "Microsoft Lumia 430 RM-10",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"description": "Смартфон Microsoft Lumia 430 RM-1099 black Куда бы вы ни направлялись, смартфон должен быть надежным спутником. Поэтому у Microsoft Lumia 430 Dual SIM (RM-1099) удобный компактный корпус",
		"vendorСode": "283135",
		"price": "5390"
	},
	{
		"title": "Senseit L301 Black",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"description": "Смартфон Senseit L301 black, черный. Micro-SIM, две поддерживаемых SIM-карты, Android, 3G, GPS-модуль",
		"vendorСode": "283135",
		"price": "4990"
	},
	{
		"title": "HIGHSCREEN WinWin Black",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"description": "Смартфон HIGHSCREEN WinWin Black оснащен 4 дисплеем и двумя слотами для SIM-карт. Windows Phone, 3G, Bluetooth, USB-подключение к ПК",
		"vendorСode": "283135",
		"price": "3990"
	},
	{
		"title": "Alcatel OT4013D PIXI 3 (2 SIM)",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"description": "Смартфон Смартфон Alcatel OT4013D PIXI 3 (2 SIM). Смартфон Alcatel One Touch 4013D оснащен четырехдюймовым дисплеем и двумя слотами для SIM-карт",
		"vendorСode": "283135",
		"price": "3290"
	},
	{
		"title": "Fly IQ434 Era Nano 5",
		"sim": "Micro-SIM",
		"simAmount": "2",
		"color": "Белый",
		"os": "Windows Phone",
		"_3g": "Есть",
		"_4g": "Нет",
		"gps": "A-GPS",
		"description": "Смартфон Fly IQ434 Era Nano 5 оснащен 3.5' дисплеем и двумя слотами для SIM-карт. Android 2.3, Micro SD, Wi-Fi",
		"vendorСode": "283135",
		"price": "1790"
	}]
}